### ISSUE TITLE
Common format for tuning is not accepted

### ISSUE THREAD

**Issue by ennorom** [xzippyzachx/softwareproject_group9#17] opened 2021-03-25 01:44 UTC
ID#: 17

Who raised: Elijah Nnorom

Title: Common format for tuning is not accepted

Version: Github commit 823856f in the master branch

Platform: Windows 10

Reproduction:
- Get guitar tablature into the window via copy and paste OR drag and drop
- Make sure the tuning on the first string starts with an "E" rather than "e"
- Click the convert button

Expected: This should have converted the guitar tablature to a musicxml and request the directory where you would like to have the file saved.

Actual: This causes an error "Tune Not Recognized"

Priority: low

Severity: low

Screenshots:
![image](https://user-images.githubusercontent.com/45472071/112405991-bbbe1f80-8ce9-11eb-88b8-d8a66dd849c9.png)

**Comment by xzippyzachx** [comment] 2021-04-08 03:55
This issue has been fixed and is a duplicate of https://github.com/xzippyzachx/softwareproject_group9/issues/24

**Closed as completed by xzippyzachx** 2021-04-08 03:55 UTC
Labels: bug, duplicate
